/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.awt.AWTException;
import java.io.IOException;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, AWTException, IOException {
        // // TestCases tests = new TestCases(); // Initialize your test class
        // //TODO: call your test case functions one after other here
        // //END Tests
        // End your test by clearning connections and closing browser

        //1.Test Case - Amazon
        // AmazonSearch search = new AmazonSearch();
        // search.testCase01();
        // search.endTest();

        // //2.Test Case - BookMyShow
        // Bookmyshow hyperlinks = new Bookmyshow();
        // hyperlinks.BookMyShow();
        // hyperlinks.endTest();

        // //3.LinkedIn Post
        // CreatePost post = new CreatePost();
        // post.CreatingPost();
        // post.endTest();

        // //4.Test Case - Google Name Links
        // GoogleNameLinks links = new GoogleNameLinks();
        // links.CountLinks();
        // links.endTest();

        //5.Nested Frames Text
        // NestedFramesText text = new NestedFramesText();
        // text.frame();
        // text.endTest();

        // // //6.Image/Video post LinkedIn
        // ImageLinkedin post = new ImageLinkedin();
        // post.imagepost();
        // post.endTest();
        

        //7.Alert Prompt
        // AlertPromt promtAlert = new AlertPromt();
        // promtAlert.alerthandling();
        // promtAlert.endTest();

        // //8.Window Handling 
        // WindowHandling wh = new WindowHandling();
        // wh.window();
        // wh.endTest();

        Imdb imdbRating = new Imdb();
        imdbRating.imdbTest();
        imdbRating.endTest();
        
    }

    public static void main(String[] args) throws InterruptedException, AWTException, IOException {
        new App().getGreeting();
    }
}
